#!/bin/bash

# Set variables for log file paths
CLAMAV_LOG="/var/log/clamav/clamscan.log"
RKHUNTER_LOG="/var/log/rkhunter.log"
SNORT_LOG="/var/log/snort/alert"

# Set variable for current date and time
DATETIME=$(date '+%Y-%m-%d_%H-%M-%S')

# Run ClamAV system-wide scan and save logs
clamscan -r --bell --exclude-dir="^/sys" --exclude-dir="^/proc" --exclude-dir="^/dev" --exclude-dir="^/run" --exclude-dir="^/var/lib/docker" --exclude-dir="^/var/lib/lxcfs" -i / | tee /var/log/clamav/clamscan_$DATETIME.log

# Run Rootkit Hunter system-wide scan and save logs
rkhunter --checkall --rwo --enable all --logfile $RKHUNTER_LOG | tee /var/log/rkhunter_$DATETIME.log

# Run Snort system-wide scan and save logs
snort -c /usr/local/etc/snort/snort.conf -l /var/log/snort/ -A console -i <interface> | tee /var/log/snort/snort_$DATETIME.log
