#!/bin/bash

# if you dont want to delete the cluster as well as the node then take out the code for deleting the cluster



# first, turn off node you want to remove


# Set the node name to be deleted ex. pve1
NODE_NAME="pve1"







# Remove Node from cluster

pvecm nodes
pvecm delnode "${NODE_NAME}"
wait
reboot

# Wait for the node to come back online




# DELETE CLUSTER

pvecm expected 1
wait




# Stop the running cluster

systemctl stop pve-cluster
wait




# Force the nodes to run in local mode

pmxcfs -l
wait




# Delete all the cluster configuration files

rm -f /etc/pve/cluster.conf /etc/pve/corosync.conf
rm -f /etc/cluster/cluster.conf /etc/corosync/corosync.conf
rm /var/lib/pve-cluster/.pmxcfs.lockfile
wait




# Stop cluster from running

systemctl stop pve-cluster
wait




# Delete the node's authkey

rm /etc/corosync/authkey




# Reboot the node to complete the removal process

reboot
