#!/bin/bash
# if .ssh folder isnt created yet for current user
if [ ! -d ~/.ssh/ ]; then
  mkdir ~/.ssh/
fi

# Generate the 4096-bit RSA key pair
ssh-keygen -b 4096 -t rsa

# Copy the public key to the remote server
ssh-copy-id user@ip.com
